version: '3.0'
services:
  teddit-app:
    container_name: teddit-app
    image: ghcr.io/nikurasukun/teddit:latest
    environment:
      - DOMAIN= #Your Domain 
      - TRUST_PROXY=true # enable if using reverse proxy
      - REDIS_HOST=teddit-redis
      - NO_SSL_PORT=42080
      - API_ENABLED=true # enable the api on your instance
    ports:
      - 42080:42080
    networks:
      - teddit_net
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/about"]
      interval: 1m
      timeout: 3s
    depends_on:
      - teddit-redis

  teddit-redis:
    container_name: teddit-redis
    image: redis:6.2.5-alpine
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - teddit_net

networks:
  teddit_net:
